### ISSUE TITLE
How to use in QtCreator

### ISSUE THREAD

**Issue by EndrII** [albertodonato/pyls-snap#1]
Hi.
i am install this package, but module pyls not found.

``` bash
sudo snap install pyls
```

``` bash
 andrei@X570-GAMING-X:~$ /usr/bin/python3 -m pyls
/usr/bin/python3: No module named pyls
```

**Comment by albertodonato** [comment]
Hi, the snap is self-contained. After installing it you'll have the `pyls` command available.

**Comment by EndrII** [comment]
i try run pyls.
but this is still not working for me
```
andrei@X570-GAMING-X:~$ pyls
Traceback (most recent call last):
  File "/home/andrei/.local/bin/pyls", line 5, in <module>
    from pyls.__main__ import main
ModuleNotFoundError: No module named 'pyls'

```

**Comment by albertodonato** [comment]
That's not the `pyls` command from the snap, it must be from a local `pip install python-language-server` you have previously run.

The snap binary would be `/snap/bin/pyls`.

**Comment by EndrII** [comment]
It is work!
Thank )
